server.port=8081
spring.application.name=ga-rolltrade-pred
spring.servlet.multipart.max-file-size=16MB
spring.servlet.multipart.max-request-size=16MB
spring.thymeleaf.cache=false
logging.level.com.example.quant=INFO
